

---
Savitribai Phule Pune University   
Second Year of Computer Engineering (2019 Course) 210246:

# **Data Structures Laboratory**
---

> ### **GROUP-A**


**Problem Statement:-**

Write a Python program that determines the location of a saddle point of matrix if one exists. An m x n matrix is said to have a saddle point if some entry a[i][j] is the smallest value in row i and the largest value in j. 

In [44]:
import numpy as np

In [45]:
def take_input(n):
  matrix = np.zeros((n , n) , dtype=int)
  print("Matrix innput:-")
  for i in range(0,n):
    for j in range(0,n):
      val = int(input(f"Enter number at position {i+1,j+1}:-"))
      matrix[i][j] = val
  return np.array(matrix)


In [46]:
n = int(input("\n Enter the dimention of the matrix:-"))
matrix = take_input(n)
print(matrix)
print()
for i in range(n):
  for j in range(n):
    minimum = min(matrix[i])
    maximum = max(matrix[:,j])
    if minimum == maximum:
      print(f"Saddle point is exist at row-{i+1} and column-{j+1}:-", minimum)


 Enter the dimention of the matrix:-3
Matrix innput:-
Enter number at position (1, 1):-3
Enter number at position (1, 2):-4
Enter number at position (1, 3):-5
Enter number at position (2, 1):-6
Enter number at position (2, 2):-7
Enter number at position (2, 3):-8
Enter number at position (3, 1):-9
Enter number at position (3, 2):-10
Enter number at position (3, 3):-11
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Saddle point is exist at row-3 and column-1:- 9
